apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .name }}
spec:
  selector:
    {{- range $key, $value := .selector }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
  servers:
    - port:
        number: {{ .Values.gateways.port.number }}
        name: {{ .Values.gateways.port.name }}
        protocol: {{ .Values.gateways.port.protocol }}
      hosts:
        - "{{ range $value := .hosts }}{{ $value }}{{ end }}"
{{- end }}

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .name }}
spec:
  hosts:
    - "{{ range $value := .hosts }}{{ $value }}{{ end }}"
  gateways:
    - "{{ range $value := .gateways }}{{ $value }}{{ end }}"
  http:
    {{- range .http }}
    - match:
        {{- range .match }}
        - uri:
            {{- range $key, $value := . }}
            {{ $key }}: "{{ $value }}"
            {{- end }}
        {{- end }}
      route:
        - destination:
            host: {{ .Values.virtualServices.http.route.destination.host }}
            port:
              number: {{ .Values.virtualServices.http.route.destination.port.number }}
    {{- end }}
{{- end }}
