apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-app
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-gitops
  project: default
  source:
    repoURL: https://github.com/sanjaytripathi97/bookinfo-chart.git
    path: kuard-chart/application-set
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true