apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-instance
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: green-v1
        url: https://kubernetes.default.svc
      - cluster: green-v2
        url: https://kubernetes.default.svc
      - cluster: blue-v1
        url: https://kubernetes.default.svc
      - cluster: blue-v2
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: application-instance-{{cluster}}
      namespace: openshift-gitops
    spec:
      destination:
        server: https://kubernetes.default.svc
      project: default
      source:
        path: kuard-chart/green/{{ cluster }}/chart
        repoURL: https://github.com/sanjaytripathi97/bookinfo-chart.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true