apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kuard
    version: {{ .Values.version }}
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuard
      version: {{ .Values.version }}
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "{{ .Values.sidecar }}"
      creationTimestamp: null
      labels:
        app: kuard
        version: {{ .Values.version }}
    spec:
      containers:
      - image: {{ .Values.image }}
        name: kuar-amd64
        ports:
        - containerPort: 8080
        resources: {}