services:
  details:
    ports:
      http: 9080

  ratings:
    ports:
      http: 9080

  reviews:
    ports:
      http: 9080

  productpage:
    ports:
      http: 9080

deployments:
  details:
    image: quay.io/maistra/examples-bookinfo-details-v1:2.4.0
    replicas: 1

  ratings:
    image: quay.io/maistra/examples-bookinfo-ratings-v1:2.4.0
    replicas: 1

  reviews:
    v1:
      image: quay.io/maistra/examples-bookinfo-reviews-v1:2.4.0
      replicas: 1
    v2:
      image: quay.io/maistra/examples-bookinfo-reviews-v2:2.4.0
      replicas: 1
    v3:
      image: quay.io/maistra/examples-bookinfo-reviews-v3:2.4.0
      replicas: 1

  productpage:
    image: quay.io/maistra/examples-bookinfo-productpage-v1:2.4.0
    replicas: 1

serviceAccounts:
  details: bookinfo-details
  ratings: bookinfo-ratings
  reviews: bookinfo-reviews
  productpage: bookinfo-productpage

destinationRules:
  - metadata:
      name: productpage
    spec:
      host: productpage
      subsets:
        - name: v1
          labels:
            version: v1

  - metadata:
      name: reviews
    spec:
      host: reviews
      subsets:
        - name: v1
          labels:
            version: v1
        - name: v2
          labels:
            version: v2
        - name: v3
          labels:
            version: v3

  - metadata:
      name: ratings
    spec:
      host: ratings
      subsets:
        - name: v1
          labels:
            version: v1
        - name: v2
          labels:
            version: v2
        - name: v2-mysql
          labels:
            version: v2-mysql
        - name: v2-mysql-vm
          labels:
            version: v2-mysql-vm

  - metadata:
      name: details
    spec:
      host: details
      subsets:
        - name: v1
          labels:
            version: v1
        - name: v2
          labels:
            version: v2

gateways:
  - name: bookinfo-gateway
    selector:
      istio: ingressgateway
    port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*"

virtualServices:
  - name: bookinfo
    hosts:
      - "*"
    gateways:
      - bookinfo-gateway
    http:
      - match:
          - uri:
              exact: /productpage
          - uri:
              prefix: /static
          - uri:
              exact: /login
          - uri:
              exact: /logout
          - uri:
              prefix: /api/v1/products
        route:
          - destination:
              host: productpage
              port:
                number: 9080
