services:
  details:
    ports:
      http: 9080

  ratings:
    ports:
      http: 9080

  reviews:
    ports:
      http: 9080

  productpage:
    ports:
      http: 9080

deployments:
  details:
    image: quay.io/maistra/examples-bookinfo-details-v1:2.4.0
    replicas: 1

  ratings:
    image: quay.io/maistra/examples-bookinfo-ratings-v1:2.4.0
    replicas: 1

  reviews:
    v1:
      image: quay.io/maistra/examples-bookinfo-reviews-v1:2.4.0
      replicas: 1
    v2:
      image: quay.io/maistra/examples-bookinfo-reviews-v2:2.4.0
      replicas: 1
    v3:
      image: quay.io/maistra/examples-bookinfo-reviews-v3:2.4.0
      replicas: 1

  productpage:
    image: quay.io/maistra/examples-bookinfo-productpage-v1:2.4.0
    replicas: 1

serviceAccounts:
  details: bookinfo-details
  ratings: bookinfo-ratings
  reviews: bookinfo-reviews
  productpage: bookinfo-productpage


gateways:
    name: bookinfo-gateway
    selector:
      istio: ingressgateway
    port:
      number: 80
      name: http
      protocol: HTTP

virtualServices:
    name: bookinfo
    gateways:
       bookinfo-gateway
    http:
      route:
           destination:
             host: productpage
             port:
               number: 9080
